apiVersion: v2
name: platform-infra
description: A Helm chart for Platform Infrastructure (e.g. Redis)
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: redis
    version: 18.0.0
    repository: oci://registry-1.docker.io/bitnami/redis
