apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-service.fullname" . }}-config
  labels:
    {{- include "base-service.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "environment": "production",
      "feature_x_enabled": true
    }
